---

- hosts: all
  sudo: yes
  roles:
    - hadoop

- hosts: namenode
  sudo: yes
  roles:
    - hadoop/namenode

- hosts: datanode
  sudo: yes
  roles:
    - hadoop/datanode

- hosts: resourcemanager
  sudo: yes
  roles:
    - hadoop/resourcemanager

- hosts: nodemanager
  sudo: yes
  roles:
    - hadoop/nodemanager
